### ISSUE TITLE
Support for Class-based Projections (DTOs)

### ISSUE THREAD

**Issue by 1-alex98** [spring-projects/spring-data-elasticsearch#1848] opened 2021-06-22 12:29 UTC
https://docs.spring.io/spring-data/commons/docs/2.5.1/reference/html/#projections.dtos
This already works with a workaround. It works by adding `@Document` with the correct index to the dto. The issue is that the index is read only from return type of the method:
https://github.com/spring-projects/spring-data-elasticsearch/blob/bc4c913a978cd99f556dbe89c1b39f9aeec3654c/src/main/java/org/springframework/data/elasticsearch/repository/query/ElasticsearchPartQuery.java#L82
Also the case in other places...

**Comment by sothawo** [comment] 2021-06-22 13:18
Of course you can use a different Entity and read from an existing index. You can for example index a `Person` entity with first and last name, an addresss, a birthday and more data and then use a different repository with a class that has only a first and last name field to read data from this index. But in the background that means that all available fields are transferred from ES to the application and then a reduced object is instantiated.

The idea for having repositoy methods returning a projection is to analyze the returned projection and to only retrieve the required fields for this projection from Elasticsearch and not the whole object. There already is an open issue #1378 for this.

**Comment by 1-alex98** [comment] 2021-06-25 08:20
I would like to use the "projection" in the same repo (as descibed in spring data commons) and would expect it do use in the same repository. So would right now then the wrong index(of the projection) is querried.

**Comment by 1-alex98** [comment] 2021-06-25 10:50
https://github.com/spring-projects/spring-data-elasticsearch/issues/1378 goes further than what I thought of.

**Comment by sothawo** [comment] 2021-06-25 19:11
Projections don't have their own repository. They are used to make repository methods
* change the query so that only the requested fields are transferred from Elasticsearch
* return instances of the projection type

That's what #1378 is for, so I think we can close this issue as a duplicate of that one.

**Closed by sothawo** 2021-06-25 19:11 UTC
Labels: status: feedback-provided, status: waiting-for-triage
