### ISSUE TITLE
Java 17: InaccessibleObjectException due to illegal reflective access when saving entities containing a BigDecimal

### ISSUE THREAD

**Issue by ostecke** [spring-projects/spring-data-elasticsearch#2037] opened 2021-12-23 14:36 UTC
I'm currently trying to migrate a project from Java 11 to Java 17 and I'm not able to get any code running when saving an entity containing a BigDecimal object in ElasticSearch. When trying to do so, I run into the following exception: 

```
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.math.BigInteger java.math.BigDecimal.intVal accessible: module java.base does not "opens java.math" to unnamed module @2758fe70
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:787)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710)
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:401)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:365)
	at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:568)
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:526)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710)
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:401)
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:365)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:258)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:201)
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:87)
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:73)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.getRequiredPersistentEntity(AbstractElasticsearchTemplate.java:646)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.getIndexCoordinatesFor(AbstractElasticsearchTemplate.java:583)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.save(AbstractElasticsearchTemplate.java:180)
	at com.redacted.ComponentTest.saveBigDecimal(ComponentTest.java:84)
``` 

I created two tests to check where the problem may lie. The Integer test succeeds, yet the BigDecimal test fails with the above exception. 

```
@Test
  public void saveBigDecimal() {
    elasticsearchRestTemplate.save(new BigDecimalWrapper());
  }

  @Test
  public void saveInteger() {
    elasticsearchRestTemplate.save(new IntegerWrapper());
  }

  @Document(indexName = "bigDecimal-wrapper")
  static class BigDecimalWrapper{
    BigDecimal one = BigDecimal.ONE;
    BigDecimal ten = BigDecimal.TEN;
    String someString = "yeah";
  }

  @Document(indexName = "integer-wrapper")
  static class IntegerWrapper{
    Integer one = 1;
    int ten = 10;
    String someString = "yeah";
  }
```

![image](https://user-images.githubusercontent.com/22278221/147254576-0cb22cc6-863e-4a3b-85e1-6ed097c7eeb1.png)

To run this I am using Java 17 with SpringBoot 2.5.8 containing Spring Data ElasticSearch 4.2.7. I'm happy to provide more details if necessary, please let me know.

**Comment by sothawo** [comment] 2021-12-23 21:33
I cannot reproduce this behaviour. I have a Spring Boot (2.5.8) application, Spring Data Elasticsearch 4.2.7 and I added the following class (note that the index name _bigDecimal-wrapper_ is illegal, this would throw an error in Elasticsearch):

```java
@RestController
@RequestMapping("/bigdecimal")
public class BigDecimalTestController {

	private static Logger LOGGER = LoggerFactory.getLogger(BigDecimalTestController.class);

	private final ElasticsearchOperations operations;

	public BigDecimalTestController(ElasticsearchOperations operations) {
		this.operations = operations;
	}

	@GetMapping
	public void test(){
		var savedInt = operations.save(new IntegerWrapper());
		var loadedInt = operations.get(savedInt.id, IntegerWrapper.class);
		LOGGER.info(loadedInt.toString());

		var savedBigDecimal = operations.save(new BigDecimalWrapper());
		var loadedBigDecimal = operations.get(savedBigDecimal.id, BigDecimalWrapper.class);
		LOGGER.info(loadedBigDecimal.toString());
	}

	@Document(indexName = "bigdecimal-wrapper")
	static class BigDecimalWrapper{
		@Id
		String id;
		BigDecimal one = BigDecimal.ONE;
		BigDecimal ten = BigDecimal.TEN;
		String someString = "yeah";

		@Override
		public String toString() {
			return "BigDecimalWrapper{" +
				"id='" + id + '\'' +
				", one=" + one +
				", ten=" + ten +
				", someString='" + someString + '\'' +
				'}';
		}
	}

	@Document(indexName = "integer-wrapper")
	static class IntegerWrapper{
		@Id
		String id;
		Integer one = 1;
		int ten = 10;
		String someString = "yeah";

		@Override
		public String toString() {
			return "IntegerWrapper{" +
				"id='" + id + '\'' +
				", one=" + one +
				", ten=" + ten +
				", someString='" + someString + '\'' +
				'}';
		}
	}
}
```

This runs without problems with both Java 11 and Java 17.

How have you configured Spring Data Elasticsearch in your application? It seems that somehow the BigDecimal is not mapped and that in your setup the `BigDecimal` is treated like a Java Bean (try to access the `intValue` private field).

Can you please provide a minimal buildable project that reproduces the error?

**Comment by SeanAda** [comment] 2021-12-31 16:07
I've got the same issue with Java 17 and Spring Boot 2.6.2 with Spring Data Elasticsearch.

The document class (in Kotlin) looks like this:

```
@Document(indexName = "test-document")
@Setting(settingPath = "/elasticsearch/xxx-analyser.json")
data class TestDocument(

        ...

        val compensationValue: BigDecimal,

      ...
```

The exception is:

```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.math.BigInteger java.math.BigDecimal.intVal accessible: module java.base does not "opens java.math" to unnamed module @79d8407f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[na:na]
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[na:na]
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178) ~[na:na]
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172) ~[na:na]
	at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:787) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:549) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:423) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:380) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.lambda$createAndRegisterProperty$3(AbstractMappingContext.java:604) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:601) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:555) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.data.mapping.context.AbstractMappingContext.doAddPersistentEntity(AbstractMappingContext.java:423) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:380) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:265) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:208) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:91) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$6(RepositoryFactoryBeanSupport.java:325) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:325) ~[spring-data-commons-2.6.0.jar:2.6.0]
	at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:69) ~[spring-data-elasticsearch-4.3.0.jar:4.3.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.14.jar:5.3.14]
```

There is no special configuration in the application.yml.

**Comment by sothawo** [comment] 2021-12-31 17:09
Please provide a sample project with which this can be reproduced.

**Comment by SeanAda** [comment] 2022-01-01 18:04
Here is the sample project to reproduce the exception: https://github.com/SeanAda/Elastic-InaccessibleObjectException-

**Comment by sothawo** [comment] 2022-01-02 08:32
You need to derive your configuration class from `AbstractElasticsearchConfiguration` like it's shown in [the documentation](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#elasticsearch.clients.rest). 

This not only creates the client but also initializes the internal objects like `ElasticsearchMapper` or the registered conversions. Spring Data Elasticsearch has some internal conversions built in, one is for converting `BigDecimal` to `Double` and back. (Elasticsearch does not support `BigDecimal` types, see https://www.elastic.co/guide/en/elasticsearch/reference/7.16/number.html).

So your configuration class would be (the second bean you had is provided by the base class already):
```kotlin
@Configuration
@EnableElasticsearchRepositories(basePackages = ["com.example"])
class ElasticsearchConfig(private val elasticsearchProperties: ElasticsearchProperties) : AbstractElasticsearchConfiguration() {
	@Bean
	override fun elasticsearchClient(): RestHighLevelClient {

		val clientConfiguration: ClientConfiguration = ClientConfiguration.builder()
			.connectedTo(elasticsearchProperties.url)
			.withBasicAuth(elasticsearchProperties.username, elasticsearchProperties.password)
			.build()
		return RestClients.create(clientConfiguration)
			.rest()
	}
}
```

Besides that, I'd recommend to add `@Field` annotations to your entity, so that when the application starts and the index is created, a correct mapping is written to the index; otherwise the type to use will be subject to Elasticsearch  autodetection:

```kotlin
@Document(indexName = "testmodel")
data class TestModel(

	@Id
	val id: String,

	@Field(type = FieldType.Text)
	val test: String,

	@Field(type = FieldType.Double)
	val testValue: BigDecimal,
)
```

**Comment by SeanAda** [comment] 2022-01-02 12:50
Perfect it is working right now :) Thank you for your quick answer!

Best regards from Wuppertal

**Comment by sothawo** [comment] 2022-01-02 17:46
@ostecke does this solve your problem as well?

**Comment by spring-projects-issues** [comment] 2022-01-16 10:07
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-01-23 10:07
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-01-23 10:07 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder

**Comment by ameltonyan** [comment] 2022-02-28 19:54
> 

I have the same problem and extending from AbstractElasticsearchConfiguration class solves the problem.
Thanks a lot.
