### ISSUE TITLE
Incorrect parameters escaping in @Query

### ISSUE THREAD

**Issue by gerardolenski** [spring-projects/spring-data-elasticsearch#1798] opened 2021-05-01 18:59 UTC
Hi guys,

I'm using Spring Data Elasticsearch 3.2.12.RELEASE along with Spring Boot 2.2.13.RELEASE and found an issue regarding escaping special characters using `@Query` annotation in the repository. Here are the details:

**Preconditions:**
Let's say I'm having ES document with the keyword field e.g:
```
@Field(type = FieldType.Keyword)
private String foo;
```
Now I've got the repository and want to use `term query` to exact match by my field:
```
@Query("{\"bool\": {\"must\": [{\"term\": {\"foo\": {\"value\": \"?0\"}}}]}}")
Page<FooDocument> findByFoo(String foo, Pageable pageable);
```
The document was indexed with the value: `my "foo" keyword`

**When:**
trying to use `findByFoo` let's say:
```
fooRepository.findByFoo("my \"foo\" keyword", PageRequest.of(0, 100))
```

**Then:**
I'm receiving the exception:
```
UncategorizedExecutionException[Failed execution
]; nested: IOException[Unexpected character ('f' (code 102)): was expecting comma to separate Object entries
 at [Source: [B@c355fcd; line: 1, column: 145]];
	at org.elasticsearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:97)
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:62)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:1042)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.getSearchResponse(ElasticsearchTemplate.java:1038)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:450)
	at org.springframework.data.elasticsearch.core.ElasticsearchTemplate.queryForPage(ElasticsearchTemplate.java:445)
	at org.springframework.data.elasticsearch.repository.query.ElasticsearchStringQuery.execute(ElasticsearchStringQuery.java:70)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:619)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:606)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.redbend.vinspecific.generic.module.terminalspecific.$Proxy207.findByDomainIdAndProcessCorrelator(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
```

The same occurs even when tried to double escape the query parameter:
```
fooRepository.findByFoo("my \\\"foo\\\" keyword", PageRequest.of(0, 100))
```

**Additional information**
During debugging  IMO the problem is in `ElasticsearchStringQuery#replacePlaceholders` method when the JSON string is not correctly formatted when e.g `'\"'` or `'\\'` character was used in the replacing parameter. The JSON query which is sent to Elastic looks like this:
```
{"bool": {"must": [ {"term": {"foo": {"value": "my "foo" keyword"}}}]}}
```
but should be:
```
{"bool": {"must": [ {"term": {"foo": {"value": "my \"foo\" keyword"}}}]}}
```

**Comment by sothawo** [comment] 2021-05-03 21:08
Duplicate of #1790, the fix has been backported to the 3.2.x branch and will be contained in the next service release.

**Closed by sothawo** 2021-05-03 21:08 UTC
Labels: status: waiting-for-triage
